fix: NPE
2026-01-23 16:10:03.284 [RaftRepClient2IoWorker] WARN  c.g.dtprj.dongting.net.NioWorker - process socket write error, channel will close
java.lang.NullPointerException: Cannot assign field "nextInChannel" because "dtc.pendingReqTail" is null
	at dongting.client@0.8.4-SNAPSHOT/com.github.dtprj.dongting.net.WorkerStatus.addPendingReq(WorkerStatus.java:153)
	at dongting.client@0.8.4-SNAPSHOT/com.github.dtprj.dongting.net.IoChannelQueue.getWriteBuffer(IoChannelQueue.java:175)
	at dongting.client@0.8.4-SNAPSHOT/com.github.dtprj.dongting.net.NioWorker.processOneSelectionKey(NioWorker.java:335)
	at dongting.client@0.8.4-SNAPSHOT/com.github.dtprj.dongting.net.NioWorker.run0(NioWorker.java:200)
	at dongting.client@0.8.4-SNAPSHOT/com.github.dtprj.dongting.net.NioWorker.run(NioWorker.java:144)
	at java.base/java.lang.Thread.run(Thread.java:1583)